using AppUpdater.Models;
using Microsoft.Maui.LifecycleEvents;

namespace AppUpdater;

public static class AppBuilderExtensions_shared
{
    /// <summary>
    /// Initializes the .NET MAUI Community Toolkit Library
    /// </summary>
    /// <param name="builder"><see cref="MauiAppBuilder"/> generated by <see cref="MauiApp"/> </param>
    /// <param name="options"><see cref="UpdaterOptions"/></param>
    /// <returns><see cref="MauiAppBuilder"/> initialized for <see cref="Updater"/></returns>
    public static MauiAppBuilder UseUpdater(this MauiAppBuilder builder, Action<UpdaterOptions>? options = default)
    {
        options?.Invoke(new UpdaterOptions(builder));

        builder.Services.AddSingleton<IUpdaterService, UpdaterService>();

        return builder;
    }
}